theme = "beautifulhugo"
baseURL = "https://ct-data-haven.github.io/"
publishDir = "../ct-data-haven.github.io"
languageCode = "en-us"
title = "DataHaven extras"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[Params]
  subtitle = "B-sides and side projects"
  commit = false
  readingTime = false
  useHLJS = true
  socialShare = true
  logo = "img/avatar-icon.png"
  favicon = "img/favicon.ico"
  
[Author]
  name = "DataHaven"
  website = "www.ctdatahaven.org"
  facebook = "connecticutdata"
  github = "ct-data-haven"
  twitter = "ctdata"
  
[[menu.main]]
  name = "Project list"
  url = ""
  weight = 1
  
[[menu.main]]
  name = "About"
  url = "page/about"
  weight = 2
  
[[menu.main]]
  name = "Tags"
  url = "tags" 
  weight = 3